# Generated by Django 5.0.1 on 2026-01-13 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=255, verbose_name='Customer Name')),
                ('phone_number', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='PIN Code')),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=15, null=True, verbose_name='GSTIN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('total_invoices', models.IntegerField(default=0, help_text='Total number of invoices generated for this customer', verbose_name='Total Invoices')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total billing amount across all invoices', max_digits=12, verbose_name='Total Amount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_name'], name='customers_custome_147306_idx'), models.Index(fields=['phone_number'], name='customers_phone_n_7d2329_idx'), models.Index(fields=['is_active'], name='customers_is_acti_0e47e3_idx'), models.Index(fields=['created_at'], name='customers_created_c63477_idx')],
            },
        ),
    ]
