# Generated by Django 5.0.1 on 2026-01-13 11:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Standard Steels & Hardware', max_length=255, verbose_name='Company Name')),
                ('company_address', models.TextField(default='123 Industrial Area, Steel City', verbose_name='Company Address')),
                ('phone_number', models.CharField(default='+91 12345 67890', max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(default='info@standardsteels.com', max_length=255, verbose_name='Email Address')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('gstin', models.CharField(blank=True, help_text='Company GST Identification Number', max_length=15, null=True, verbose_name='GSTIN')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Company Logo')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Default GST/Tax rate for invoices', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Default Tax Rate (%)')),
                ('tax_label', models.CharField(default='GST', help_text='Label for tax field (e.g., GST, VAT, Tax)', max_length=50, verbose_name='Tax Label')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10, verbose_name='Invoice Number Prefix')),
                ('invoice_start_number', models.IntegerField(default=500000, verbose_name='Invoice Start Number')),
                ('invoice_terms', models.TextField(default='Terms & Conditions Apply | This is a computer generated invoice', verbose_name='Default Invoice Terms')),
                ('invoice_footer', models.TextField(blank=True, null=True, verbose_name='Invoice Footer Text')),
                ('payment_due_days', models.IntegerField(default=30, help_text='Default number of days for payment due date', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Payment Due Days')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
    ]
